ANALYSIS_EXTRA_SLIDING_WINDOW_MODULE_NAME := analysis/extra_sliding_window
SUBMODULES := 

ANALYSIS_EXTRA_SLIDING_WINDOW_SUBMODULES := $(foreach weight,$(EXTRA_SLIDING_WINDOW_WEIGHTS),$(addprefix $(ANALYSIS_EXTRA_SLIDING_WINDOW_MODULE_NAME)/window_,$(weight)))
$(ANALYSIS_EXTRA_SLIDING_WINDOW_MODULE_NAME): $(ANALYSIS_EXTRA_SLIDING_WINDOW_SUBMODULES)

define analysis-extra_sliding-makefiles
MODULE_NAME := $(1)
include $(COMMON_ANALYSIS_MAKEFILE)
endef

$(foreach m,$(ANALYSIS_EXTRA_SLIDING_WINDOW_SUBMODULES),$(eval $(call analysis-extra_sliding-makefiles,$(m))))

$(ANALYSIS_EXTRA_SLIDING_WINDOW_MODULE_NAME)/clean:
	rm -rf $(ANALYSIS_EXTRA_SLIDING_WINDOW_SUBMODULES)
